// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 28 Feb 2016 23:09:26 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

int MDB_cmp_func_15aea10f(MDB_val* a, MDB_val* b) {
	return cmpFunc15AEA10F(a, b);
}

void MDB_rel_func_3a9876a5(MDB_val* item, void* oldptr, void* newptr, void* relctx) {
	relFunc3A9876A5(item, oldptr, newptr, relctx);
}

void MDB_assert_func_635f7c32(MDB_env* env, char* msg) {
	assertFunc635F7C32(env, msg);
}

int MDB_msg_func_86d0dcef(char* msg, void* ctx) {
	return msgFunc86D0DCEF(msg, ctx);
}

