// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 06 Jun 2016 15:47:34 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

int MDB_cmp_func_e2fae82f(MDB_val* a, MDB_val* b) {
	return cmpFuncE2FAE82F(a, b);
}

void MDB_rel_func_1510551d(MDB_val* item, void* oldptr, void* newptr, void* relctx) {
	relFunc1510551D(item, oldptr, newptr, relctx);
}

void MDB_assert_func_c5b9172d(MDB_env* env, char* msg) {
	assertFuncC5B9172D(env, msg);
}

int MDB_msg_func_de422fad(char* msg, void* ctx) {
	return msgFuncDE422FAD(msg, ctx);
}

