// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 06 Jun 2016 16:15:44 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include "lmdb.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// MDB_cmp_func_e2fae82f is a proxy for callback MDB_cmp_func.
int MDB_cmp_func_e2fae82f(MDB_val* a, MDB_val* b);

// MDB_rel_func_1510551d is a proxy for callback MDB_rel_func.
void MDB_rel_func_1510551d(MDB_val* item, void* oldptr, void* newptr, void* relctx);

// MDB_assert_func_c5b9172d is a proxy for callback MDB_assert_func.
void MDB_assert_func_c5b9172d(MDB_env* env, char* msg);

// MDB_msg_func_de422fad is a proxy for callback MDB_msg_func.
int MDB_msg_func_de422fad(char* msg, void* ctx);

