// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 07 Mar 2016 02:55:47 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package mdb provides Go bindings for liblmdb, the Symas's LMDB database library. LMDB is an ultra-fast, ultra-compact, crash-proof key-value embedded data store developed by Symas for the OpenLDAP Project. It uses memory-mapped files, so it has the read performance of a pure in-memory database while still offering the persistence of standard disk-based databases, and is only limited to the size of the virtual address space.
*/
package mdb
