// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 28 Feb 2016 23:09:26 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

package mdb

/*
#include "lmdb.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Mode type as declared in mdb/lmdb.h:179
type Mode uint16

// Size type as declared in mdb/lmdb.h:186
type Size uint

// Filehandle type as declared in mdb/lmdb.h:196
type Filehandle int32

// Env as declared in mdb/lmdb.h:239
type Env C.MDB_env

// Txn as declared in mdb/lmdb.h:246
type Txn C.MDB_txn

// Dbi type as declared in mdb/lmdb.h:249
type Dbi uint32

// Cursor as declared in mdb/lmdb.h:252
type Cursor C.MDB_cursor

// Val as declared in mdb/lmdb.h:268
type Val struct {
	MvSize         uint
	MvData         unsafe.Pointer
	reff5baf417    *C.MDB_val
	allocsf5baf417 interface{}
}

// CmpFunc type as declared in mdb/lmdb.h:271
type CmpFunc func(a *Val, b *Val) int32

// RelFunc type as declared in mdb/lmdb.h:287
type RelFunc func(item *Val, oldptr unsafe.Pointer, newptr unsafe.Pointer, relctx unsafe.Pointer)

// DbStat as declared in mdb/lmdb.h:472
type DbStat struct {
	MsPsize         uint32
	MsDepth         uint32
	MsBranchPages   Size
	MsLeafPages     Size
	MsOverflowPages Size
	MsEntries       Size
	ref9ed18a7f     *C.MDB_stat
	allocs9ed18a7f  interface{}
}

// Envinfo as declared in mdb/lmdb.h:482
type Envinfo struct {
	MeMapaddr      unsafe.Pointer
	MeMapsize      Size
	MeLastPgno     Size
	MeLastTxnid    Size
	MeMaxreaders   uint32
	MeNumreaders   uint32
	refea477e79    *C.MDB_envinfo
	allocsea477e79 interface{}
}

// AssertFunc type as declared in mdb/lmdb.h:931
type AssertFunc func(env *Env, msg string)

// MsgFunc type as declared in mdb/lmdb.h:1579
type MsgFunc func(msg string, ctx unsafe.Pointer) int32
